{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nextjs-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.metricsPath }}
      interval: {{ .Values.monitoring.interval }}
{{- end }}
